" Generated by vim-plug
" Sat Jul  1 11:34:57 2023
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-session'].commit = '7afbb149f87be279778689596c781882014f7eef'
silent! let g:plugs['better-escape.vim'].commit = '6b16a45a839727977277f6ab11bded63e9ed86bb'
silent! let g:plugs['coc.nvim'].commit = 'bbaa1d5d1ff3cbd9d26bb37cfda1a990494c4043'
silent! let g:plugs['fern.vim'].commit = 'cdec1327ec99f0155d0a53aee1beae4c58071558'
silent! let g:plugs['friendly-snippets'].commit = '5749f093759c29e3694053d048ceb940fe12c3d3'
silent! let g:plugs['fzf-lua'].commit = 'cb0943a41df4bb59475a13c4dcc7256cc230a2e3'
silent! let g:plugs['hop.nvim'].commit = '03f0434869f1f38868618198b5f4f2ab6d39aef2'
silent! let g:plugs['indent-blankline.nvim'].commit = '7075d7861f7a6bbf0de0298c83f8a13195e6ec01'
silent! let g:plugs['markdown-preview.nvim'].commit = '02cc3874738bc0f86e4b91f09b8a0ac88aef8e96'
silent! let g:plugs['minimap.vim'].commit = '726746ed02eab2eef137a7ecceda7214fbeeec41'
silent! let g:plugs['numb.nvim'].commit = '2c89245d1185e02fec1494c45bc765a38b6b40b3'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-fzf'].commit = 'a8dc4bae4c1e1552e0233df796e512ab9ca65e44'
silent! let g:plugs['nvim-notify'].commit = 'ea9c8ce7a37f2238f934e087c255758659948e0f'
silent! let g:plugs['nvim-web-devicons'].commit = '14b3a5ba63b82b60cde98d0a40319d80f25e8301'
silent! let g:plugs['onedark.vim'].commit = '4e983447f0442dba1629cdaeddfd137793d71d28'
silent! let g:plugs['splitjoin.vim'].commit = 'c00fa513974811e7bdf34b3d8a53abbd69c9042c'
silent! let g:plugs['tmuxline.vim'].commit = '4119c553923212cc67f4e135e6f946dc3ec0a4d6'
silent! let g:plugs['undotree'].commit = '485f01efde4e22cb1ce547b9e8c9238f36566f21'
silent! let g:plugs['vim-airline'].commit = '423fe9e2acbe64bd8637d0bedff132972d7603de'
silent! let g:plugs['vim-airline-themes'].commit = 'dd81554c2231e438f6d0e8056ea38fd0e80ac02a'
silent! let g:plugs['vim-commentary'].commit = 'e87cd90dc09c2a203e13af9704bd0ef79303d755'
silent! let g:plugs['vim-diminactive'].commit = '6f2e14e6ff6a038285937c378ec3685e6ff7ee36'
silent! let g:plugs['vim-fugitive'].commit = '43f18ab9155c853a84ded560c6104e6300ad41da'
silent! let g:plugs['vim-ipython-cell'].commit = '35e25f63c0de4fa3d9f9b1d8922905cd309795ce'
silent! let g:plugs['vim-lion'].commit = 'ce46593ecd60e6051fb6e4d3986d2fc9f5a618b1'
silent! let g:plugs['vim-matchup'].commit = '3a17944bfa3942da805a381750a1be4b314c64d2'
silent! let g:plugs['vim-maximizer'].commit = '2e54952fe91e140a2e69f35f22131219fcd9c5f1'
silent! let g:plugs['vim-slime'].commit = '69fd61ba2b1fe1e0c13d09fef24290ba5ed6a85f'
silent! let g:plugs['vim-smoothie'].commit = 'df1e324e9f3395c630c1c523d0555a01d2eb1b7e'
silent! let g:plugs['vim-snippets'].commit = '76e35f37aa9e47a8b7f2909de222844ae38c7007'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-terminal-help'].commit = '4ae1772f55877e041b9c11a4ce4645890aa0fed0'
silent! let g:plugs['vim-tmux-navigator'].commit = 'cdd66d6a37d991bba7997d593586fc51a5b37aa8'
silent! let g:plugs['vim-visual-multi'].commit = '724bd53adfbaf32e129b001658b45d4c5c29ca1a'

PlugUpdate!

