[".zshrc"]
    type = "file"
    url = "https://raw.githubusercontent.com/hthntts/dotfiles/main/zsh/.zshrc"
    refreshPeriod = "1h"
[".zsh"]
    type = "archive"
    url = "https://github.com/hthntts/dotfiles/archive/master.tar.gz"
    exact = true
    stripComponents = 3
    refreshPeriod = "1h"
    include = ["*/zsh/.zsh/**"]
[".zsh.plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "1h"
[".zsh.plugins/zsh-history-substring-search"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-history-substring-search.git"
    refreshPeriod = "1h"
[".zsh.plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "1h"

[".config/nvim"]
    type = "archive"
    url = "https://github.com/hthntts/dotfiles/archive/master.tar.gz"
    exact = true
    stripComponents = 4
    refreshPeriod = "1h"
    include = ["*/nvim/**"]

[".tmux.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/hthntts/dotfiles/main/tmux/.tmux.conf"
    refreshPeriod = "1h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "1h"
[".tmux/plugins/tmux-resurrect"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-resurrect.git"
    refreshPeriod = "1h"
[".tmux/plugins/tmux-yank"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-yank.git"
    refreshPeriod = "1h"

[".config/doom"]
    type = "archive"
    url = "https://github.com/hthntts/dotfiles/archive/master.tar.gz"
    exact = true
    stripComponents = 4
    refreshPeriod = "1h"
    include = ["*/doom/**"]

[".config/kitty"]
    type = "archive"
    url = "https://github.com/hthntts/dotfiles/archive/master.tar.gz"
    exact = true
    stripComponents = 4
    refreshPeriod = "1h"
    include = ["*/kitty/**"]
